-- Vehicle info expansion
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "registrationNumber" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "ifrcCode" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "organizationName" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "modelName" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "engineNumber" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "engineCapacity" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "chassisNumber" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "yearManufacture" INTEGER;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "deployedArea" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "contractExpiry" TIMESTAMP(3);
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "registrationExpiry" TIMESTAMP(3);
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "primaryImageUrl" TEXT;

CREATE TABLE IF NOT EXISTS "VehicleImage" (
  "id" TEXT PRIMARY KEY,
  "vehicleId" TEXT NOT NULL,
  "url" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "VehicleImage_vehicleId_fkey" FOREIGN KEY ("vehicleId") REFERENCES "Vehicle"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
